### ISSUE TITLE
Tree view freezes on ipad 

### ISSUE THREAD

**Issue by szech** [JustinWingChungHui/okKindredUI_typescript#20]
Replication steps:
- load a (large-ish?) tree, e.g. ola's family or our family
- scroll around + zoom in/out a bit 
- after ~20 seconds or so, the tree will stop responding

notes:
- non-fatal. browser does not crash. user can recover by tapping another ui element outside of the tree view to continue (e.g. profile or gallery)
- problem occurs in iOS 12.0, and chrome 😒, Apple iPad Air A1474
- couldn't replicate on chrome on android tablet
- seems like you need a wide tree with lots of nodes. A tall tree with few nodes doesn't cause the problem

**Comment by JustinWingChungHui** [comment]
Can you debug it?

**Comment by JustinWingChungHui** [comment]
ie set up iPad for remote debugging?

**Comment by JustinWingChungHui** [comment]
What happens on Safari on a mac?

**Comment by JustinWingChungHui** [comment]
2 issues:
- Memory leak when mnoving tree around
- Safari needs equal number of Canvas2dContext.save() and Canvas2dContext.restore() otherwise it stops working
