### ISSUE TITLE
Data Protection Rights: Certain Circumstances

### ISSUE THREAD

**Issue by szech** [JustinWingChungHui/okKindredUI_typescript#60]
we need to be more specific about these `certain circumstances`.

either we spell out what these scenarios are, or maybe link to relevant bits of ico 
e.g. https://ico.org.uk/your-data-matters/your-right-to-get-your-data-deleted/ , https://ico.org.uk/your-data-matters/your-right-to-limit-how-organisations-use-your-data/

https://github.com/JustinWingChungHui/okKindredUI_typescript/blob/754787cad21474654c878c0de54d39625fe8a51b/src/localization/english.ts#L367

**Comment by szech** [comment]
alternatively, we could think about changing the wording.
cf: wcmt "your rights"
https://www.wcmt.org.uk/privacy-and-cookies/privacy-policy#your-rights

**Comment by JustinWingChungHui** [comment]
This is based on the official GDPR template
https://gdpr.eu/privacy-notice/

**Comment by JustinWingChungHui** [comment]
When can the organisation say no?

The organisation can refuse to erase your data in the following circumstances:

    When keeping your data is necessary for reasons of freedom of expression and information (this includes journalism and academic, artistic and literary purposes).
    When the organisation is legally obliged to keep hold of your data.
    When keeping hold of your data is necessary for reasons of public health.
    When keeping your data is necessary for establishing, exercising or defending legal claims.
    When erasing your data would prejudice scientific or historical research, or archiving that is in the public interest.

The organisation can also refuse your request if it is, as the law states, “manifestly unfounded or excessive”.

If, having considered your request, the organisation decides it does not need to erase your data, it must still respond to you. It should explain to you why it believes it does not have to erase your data, and let you know about your right to complain about this decision to the ICO, or through the courts.

**Comment by JustinWingChungHui** [comment]
So we don't do these:
When keeping your data is necessary for reasons of freedom of expression and information (this includes journalism and academic, artistic and literary purposes).
When keeping hold of your data is necessary for reasons of public health.
When erasing your data would prejudice scientific or historical research, or archiving that is in the public interest.

**Comment by JustinWingChungHui** [comment]
We may have to do this if there is a criminal investigation:
When the organisation is legally obliged to keep hold of your data.
When keeping your data is necessary for establishing, exercising or defending legal claims.
